/* EnvironmentGUI.java */

/* The package of this class. */
package environment;

/* Imported classes and/or interfaces. */
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;
import control.exception.EdgeNotFoundException;
import control.exception.VertexNotFoundException;
import control.translator.EnvironmentTranslator;
import util.FileWriter;
import model.Environment;

/**
 * Implements a GUI to configure Environment objects.
 * 
 * @see EnvironmentGUI
 */
public class EnvironmentGUI extends javax.swing.JFrame {
	/* Methods. */
	/** Constructor. */
	public EnvironmentGUI() {
		UIManager.LookAndFeelInfo[] lookings = UIManager
				.getInstalledLookAndFeels();
		try {
			UIManager.setLookAndFeel(lookings[2].getClassName());
		} catch (Exception e) {
		}

		this.initComponents();
		this.environment = null;
		this.environment_panel = new EnvironmentJPanel(this, this.environment);
		this.tabbed_panel.setComponentAt(0, this.environment_panel);
	}

	/**
	 * Initiates the components of the GUI. Generated by NetBeans IDE 3.6.
	 */
	private void initComponents() {
		xml_scroll = new javax.swing.JScrollPane();
		xml_area = new javax.swing.JTextArea();
		tabbed_panel = new javax.swing.JTabbedPane();
		this.tabbed_panel.addTab("Editor", null);
		this.tabbed_panel.addTab("XML", this.xml_scroll);
		buttons_panel = new javax.swing.JPanel();
		buttons_internal_pane = new javax.swing.JPanel();
		load_button = new javax.swing.JButton();
		save_button = new javax.swing.JButton();
		close_button = new javax.swing.JButton();
		file_chooser = new javax.swing.JFileChooser();

		xml_area.setEditable(false);
		xml_scroll.setViewportView(xml_area);

		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				exitForm(evt);
			}
		});

		tabbed_panel.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				tabbed_panelStateChanged(evt);
			}
		});

		getContentPane().add(tabbed_panel, java.awt.BorderLayout.CENTER);

		buttons_panel.setLayout(new java.awt.BorderLayout());

		buttons_internal_pane.setLayout(new java.awt.GridLayout(1, 3));

		load_button.setText("Load");
		load_button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				load_buttonActionPerformed(evt);
			}
		});

		buttons_internal_pane.add(load_button);

		save_button.setText("Save");
		save_button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				save_buttonActionPerformed(evt);
			}
		});

		buttons_internal_pane.add(save_button);

		close_button.setText("Close");
		close_button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				close_buttonActionPerformed(evt);
			}
		});

		buttons_internal_pane.add(close_button);

		buttons_panel.add(buttons_internal_pane, java.awt.BorderLayout.EAST);

		getContentPane().add(buttons_panel, java.awt.BorderLayout.SOUTH);

		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit()
				.getScreenSize();
		setBounds((screenSize.width - 600) / 2, (screenSize.height - 500) / 2,
				600, 500);
		setTitle("SimPatrol Environment Editor");
	}

	/** Executed when the close button is pressed. Generated by NetBeans IDE 3.6. */
	private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {
		if (this.environment != null)
			if (JOptionPane
					.showConfirmDialog(
							this,
							"Last modifications of the environment will be lost. Are you shure?",
							"Confirm action", JOptionPane.YES_NO_OPTION,
							JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION)
				return;

		this.exitForm(null);
	}

	/** Executed when the save button is pressed. Generated by NetBeans IDE 3.6. */
	private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {
		this.environment = this.environment_panel.getEnvironment();

		if (this.environment != null) {
			this.file_chooser.setDialogTitle("Save environment");
			this.file_chooser.setDialogType(JFileChooser.SAVE_DIALOG);
			this.file_chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
			if (this.file_chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
				String path = this.file_chooser.getSelectedFile().getPath();

				FileWriter file_writer = null;
				try {
					file_writer = new FileWriter(path);
					file_writer.print(this.environment.fullToXML(0));
					file_writer.close();

					JOptionPane.showMessageDialog(this,
							"Saved environment succesfully.",
							"Successful action.",
							JOptionPane.INFORMATION_MESSAGE);
				} catch (IOException e) {
					JOptionPane.showMessageDialog(this, "An IO error ocurred.",
							"IO Error", JOptionPane.ERROR_MESSAGE);
				}
			}
		}
	}

	/** Executed when the load button is pressed. Generated by NetBeans IDE 3.6. */
	private void load_buttonActionPerformed(java.awt.event.ActionEvent evt) {
		if (this.environment != null)
			if (JOptionPane
					.showConfirmDialog(
							this,
							"Last modifications of the environment will be lost. Are you shure?",
							"Confirm action", JOptionPane.YES_NO_OPTION,
							JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION)
				return;

		this.file_chooser.setDialogTitle("Load environment");
		this.file_chooser.setDialogType(JFileChooser.OPEN_DIALOG);
		this.file_chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
		if (this.file_chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
			String path = this.file_chooser.getSelectedFile().getPath();

			try {
				this.environment = EnvironmentTranslator.getEnvironment(path);
				this.environment_panel = new EnvironmentJPanel(this,
						this.environment);
				this.tabbed_panel.setComponentAt(0, this.environment_panel);
				this.tabbed_panel.setSelectedIndex(0);
			} catch (ParserConfigurationException e) {
				JOptionPane.showMessageDialog(this,
						"Environment content is wrong.", "Parsing Error",
						JOptionPane.ERROR_MESSAGE);
			} catch (SAXException e) {
				JOptionPane.showMessageDialog(this,
						"Environment wrongly formated.", "XML Error",
						JOptionPane.ERROR_MESSAGE);
			} catch (IOException e) {
				JOptionPane.showMessageDialog(this, "An IO error ocurred.",
						"IO Error", JOptionPane.ERROR_MESSAGE);
			} catch (VertexNotFoundException e) {
				JOptionPane.showMessageDialog(this, "Given vertex not found.",
						"Inconsistent environment", JOptionPane.ERROR_MESSAGE);
			} catch (EdgeNotFoundException e) {
				JOptionPane.showMessageDialog(this, "Given edge not found.",
						"Inconsistent environment", JOptionPane.ERROR_MESSAGE);
			}
		}
	}

	/** Executed when the tabbed_panel changes. Generated by NetBeans IDE 3.6. */
	private void tabbed_panelStateChanged(javax.swing.event.ChangeEvent evt) {
		if (this.tabbed_panel.getSelectedIndex() == 1) {
			this.environment = this.environment_panel.getEnvironment();

			if (this.environment != null)
				this.xml_area.setText(this.environment.fullToXML(0));
			else
				this.xml_area.setText("");
		}
	}

	/** Exits the Application */
	private void exitForm(java.awt.event.WindowEvent evt) {
		System.exit(0);
	}

	/**
	 * Turns this class into an executable one.
	 * 
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		EnvironmentGUI gui = new EnvironmentGUI();
		gui.setVisible(true);
		JOptionPane.showMessageDialog(gui,
				"This editor is a prototype. Use it at your own risk.",
				"Attention", JOptionPane.INFORMATION_MESSAGE);
	}

	/* Attributes. */
	// added manually
	private Environment environment;
	private EnvironmentJPanel environment_panel;

	// added by Eclipse
	private static final long serialVersionUID = -3117293267172667501L;

	// added by NetBeans IDE 3.6
	// Variables declaration - do not modify
	private javax.swing.JPanel buttons_internal_pane;
	private javax.swing.JPanel buttons_panel;
	private javax.swing.JButton close_button;
	private javax.swing.JButton load_button;
	private javax.swing.JButton save_button;
	private javax.swing.JTabbedPane tabbed_panel;
	private javax.swing.JTextArea xml_area;
	private javax.swing.JScrollPane xml_scroll;
	private javax.swing.JFileChooser file_chooser;
	// End of variables declaration
}