/* Event.java */

/* The package of this class. */
package control.event;

/* Imported classes and/or interfaces. */
import view.XMLable;

/** Implements the events generated by a simulation of the patrolling task. */
public abstract class Event implements XMLable {
	/* Methods. */
	public String reducedToXML(int identation) {
		// an event doesn't have a lighter version
		return this.fullToXML(identation, 0);
	}

	public String getObjectId() {
		// an event doesn't need an id
		return null;
	}

	public void setObjectId(String object_id) {
		// an event doesn't need an id
		// so do nothing
	}

	/**
	 * Give preference to use this.fullToXML(identation, event_time).
	 * 
	 * @deprecated
	 */
	public String fullToXML(int identation) {
		return this.fullToXML(identation, 0);
	}

	/**
	 * Obtains a XML version of the event, given the identation and the time
	 * that the event occurred.
	 * 
	 * @param identation
	 *            The identation of the XML version of the event.
	 * @param time
	 *            The time the event ocurred.
	 */
	public abstract String fullToXML(int identation, double time);
}