/* Logger.java */

/* The package of this class. */
package logger;

/* Imported classes and/or interfaces. */
import java.io.IOException;
import java.util.LinkedList;
import logger.event.Event;
import model.Environment;
import model.agent.Society;
import control.simulator.Simulator;
import view.connection.UDPConnection;

/**
 * This class represents a simple logger. It might be used by aspects and other
 * logging code.
 */
public abstract class Logger {
	/* Attributes. */
	/** The UDP connections used to output the events generated by the simulator. */
	private static LinkedList<UDPConnectionAndBooleanValue> connections;

	/** The simulator that generates the logged events. */
	private static Simulator simulator;

	/* Methods. */
	/**
	 * Configures the simulator shared among the generated events.
	 * 
	 * @param simpatrol_simulator
	 *            The simulator that generates the events when simulating.
	 */
	public static void setSimulator(Simulator simpatrol_simulator) {
		simulator = simpatrol_simulator;
	}

	/**
	 * Adds a connection to the list of connections used to output the events.
	 * 
	 * @throws IOException
	 */
	public static void addConnection(UDPConnection connection)
			throws IOException {
		if (connections == null)
			connections = new LinkedList<UDPConnectionAndBooleanValue>();

		connections.add(new UDPConnectionAndBooleanValue(connection, false));
	}

	/**
	 * Closes the connections used to output the events.
	 * 
	 * @throws IOException
	 */
	public static void reset() throws IOException {
		if (connections != null) {
			for (int i = 0; i < connections.size(); i++)
				connections.get(i).CONNECTION.stopWorking();

			connections.clear();
			connections = null;
		}
	}

	/**
	 * Logs data into the console.
	 * 
	 * @param data
	 *            The data to be logged.
	 */
	public static void println(String data) {
		System.out.println(data);
	}

	/**
	 * Logs events into the remote connections.
	 * 
	 * @param event
	 *            The event to be logged.
	 */
	public static void send(Event event) {
		if (connections != null)
			for (int i = 0; i < connections.size(); i++) {
				UDPConnectionAndBooleanValue connection = connections.get(i);

				if (!connection.received_environment) {
					Environment environment = simulator.getEnvironment();

					if (environment != null) {
						try {
							connection.received_environment = connection.CONNECTION
									.send(environment.getGraph().fullToXML(0));
						} catch (IOException e) {
							e.printStackTrace();
						}

						if (connection.received_environment) {
							Society[] societies = environment.getSocieties();
							for (int j = 0; j < societies.length; j++)
								try {
									connection.received_environment = connection.CONNECTION
											.send(societies[j].fullToXML(0));
								} catch (IOException e) {
									e.printStackTrace();
								}
						}

						if (connection.received_environment)
							try {
								connection.CONNECTION.send(event.fullToXML(0,
										simulator.getElapsedTime()));
							} catch (IOException e) {
								e.printStackTrace();
							}
					}
				} else
					try {
						connection.CONNECTION.send(event.fullToXML(0, simulator
								.getElapsedTime()));
					} catch (IOException e) {
						e.printStackTrace();
					}
			}
	}
}

/**
 * Internal class that holds together an UDP connection and a boolean value
 * indicating if this connection received a XML version of the environment being
 * simulated by SimPatrol.
 */
final class UDPConnectionAndBooleanValue {
	/** The UDP connection. */
	public final UDPConnection CONNECTION;

	/**
	 * The boolean value that expresses if the connection received a XML version
	 * of the environment.
	 */
	public boolean received_environment;

	/**
	 * Constructor.
	 * 
	 * @param connection
	 *            The UDP connection.
	 * @param received_environment
	 *            TRUE if the connection received a XML version of the
	 *            environment, FALSE if not.
	 */
	public UDPConnectionAndBooleanValue(UDPConnection connection,
			boolean received_environment) {
		this.CONNECTION = connection;
		this.received_environment = received_environment;
	}
}