/* EnvironmentNotValidException.java */

/* The package of this class. */
package control.exception;

/**
 * Exception generated when a given environment's XML string contains a wrongly
 * formatted content.
 */
public class EnvironmentNotValidException extends Exception {
	/* Attributes. */
	/* Generated by Eclipse IDE. */
	private static final long serialVersionUID = -7200308905646167178L;

}
