/* Event.java */

/* The package of this class. */
package logger.event;

/* Imported classes and/or interfaces. */
import control.simulator.Simulator;
import view.XMLable;

/** Implements the events generated by a simulation of the patrolling task. */
public abstract class Event implements XMLable {
	/* Attributes. */
	/** The simulator that generates such events. */
	protected static Simulator simulator;

	/* Methods. */
	/**
	 * Configures the simulator shared among the generated events.
	 * 
	 * @param simpatrol_simulator
	 *            The simulator that generates the events when simulating.
	 */
	public static void setSimulator(Simulator simpatrol_simulator) {
		simulator = simpatrol_simulator;
	}

	public String reducedToXML(int identation) {
		// an event doesn't have a lighter version
		return this.fullToXML(identation);
	}

	public String getObjectId() {
		// an event doesn't need an id
		return null;
	}

	public void setObjectId(String object_id) {
		// an event doesn't need an id
		// so do nothing
	}
}
