/* VertexNotFoundException.java */

/* The package of this class. */
package control.exception;

/** Exception generated every time no vertex is found from a given vertex id. */
public class VertexNotFoundException extends Exception {
	/* Attributes. */
	/* Generated by Eclipse IDE. */
	private static final long serialVersionUID = 6114269559752625814L;
}
