/* EdgeNotFoundException.java */

/* The package of this class. */
package control.exception;

/** Exception generated every time no edge is found from a given edge id. */
public class EdgeNotFoundException extends Exception {
	/* Attributes. */
	/* Generated by Eclipse IDE. */
	private static final long serialVersionUID = 7445768105930992459L;
}
