/* EventTimeProbabilityDistributionGUI.java */

/* The package of this class. */
package etpd;

/* Imported classes and/or interfaces. */
import javax.swing.JDialog;
import model.etpd.EmpiricalEventTimeProbabilityDistribution;
import model.etpd.EventTimeProbabilityDistribution;
import model.etpd.NormalEventTimeProbabilityDistribution;
import model.etpd.SpecificEventTimeProbabilityDistribution;
import model.etpd.UniformEventTimeProbabilityDistribution;

/** Implements a GUI to configure EventTimeProbabilityDistribution objects.
 * 
 *  @see EventTimeProbabilityDistribution */
public class EventTimeProbabilityDistributionGUI extends JDialog {
	/* Methods */
	/** Constructor.
     * 
     *  @param owner The GUI that called this one.
     *  @param etpd The event time probability distribution to be configured. */
    public EventTimeProbabilityDistributionGUI(JDialog owner, EventTimeProbabilityDistribution etpd) {
    	super(owner, true);
    	this.initComponents();
        this.initComponents2(etpd);
    }
    
    /** Initiates the components of the GUI.
     *  Generated by NetBeans IDE 3.6. */
    private void initComponents() {//GEN-BEGIN:initComponents
        xml_scroll = new javax.swing.JScrollPane();
        xml_area = new javax.swing.JTextArea();
        type_panel = new javax.swing.JPanel();
        type_interna_panel = new javax.swing.JPanel();
        type_label = new javax.swing.JLabel();
        editing_panel = new javax.swing.JTabbedPane();
        buttons_panel = new javax.swing.JPanel();
        buttons_internal_panel = new javax.swing.JPanel();
        cancel_button = new javax.swing.JButton();
        ok_button = new javax.swing.JButton();

        xml_area.setEditable(false);
        xml_scroll.setViewportView(xml_area);

        setTitle("SimPatrol: Event time probability distribution editor");
        
        type_panel.setLayout(new java.awt.BorderLayout());

        type_interna_panel.setLayout(new java.awt.BorderLayout());

        type_label.setText("Probability distribution type ");
        type_interna_panel.add(type_label, java.awt.BorderLayout.WEST);

        type_panel.add(type_interna_panel, java.awt.BorderLayout.WEST);

        getContentPane().add(type_panel, java.awt.BorderLayout.NORTH);

        this.editing_panel.addTab("Editor", null);
        this.editing_panel.addTab("XML", this.xml_scroll);
        editing_panel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                editing_panelStateChanged(evt);
            }
        });

        getContentPane().add(editing_panel, java.awt.BorderLayout.CENTER);

        buttons_panel.setLayout(new java.awt.BorderLayout());

        buttons_internal_panel.setLayout(new java.awt.GridLayout(1, 2));

        cancel_button.setText("Cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        buttons_internal_panel.add(cancel_button);

        ok_button.setText("Ok");
        ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_buttonActionPerformed(evt);
            }
        });

        buttons_internal_panel.add(ok_button);

        buttons_panel.add(buttons_internal_panel, java.awt.BorderLayout.EAST);

        getContentPane().add(buttons_panel, java.awt.BorderLayout.SOUTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-408)/2, (screenSize.height-327)/2, 408, 327);
    }//GEN-END:initComponents     
    
    /** Complements the initiation of the components of the GUI.
     * 
     * @param etpd The event time probability distribution to be configured by the GUI. */    
    private void initComponents2(EventTimeProbabilityDistribution etpd) {
        this.etpd = etpd;
        
        if(etpd instanceof UniformEventTimeProbabilityDistribution) {
            this.etpd_panel = new UniformEventTimeProbabilityDistributionJPanel((UniformEventTimeProbabilityDistribution) etpd);
            this.type_label.setText("Uniform distribution");
        }
        else if(etpd instanceof EmpiricalEventTimeProbabilityDistribution) {
            this.etpd_panel = new EmpiricalEventTimeProbabilityDistributionJPanel((EmpiricalEventTimeProbabilityDistribution) etpd);
            this.type_label.setText("Empirical distribution");
        }
        else if(etpd instanceof NormalEventTimeProbabilityDistribution) {
            this.etpd_panel = new NormalEventTimeProbabilityDistributionJPanel((NormalEventTimeProbabilityDistribution) etpd);
            this.type_label.setText("Normal distribution");
        }
        else {
            this.etpd_panel = new SpecificEventTimeProbabilityDistributionJPanel((SpecificEventTimeProbabilityDistribution) etpd);
            this.type_label.setText("Specific event time probability");
        }
        
        this.editing_panel.setComponentAt(0, this.etpd_panel);
    }
    
    /** Executed when the ok button is pressed.
     *  Generated by NetBeans IDE 3.6. */
    private void ok_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_buttonActionPerformed
        this.etpd = this.etpd_panel.getETPD();
    	this.dispose();    	
    }//GEN-LAST:event_ok_buttonActionPerformed

    /** Executed when the cancel button is pressed.
     *  Generated by NetBeans IDE 3.6. */
    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        this.etpd = null;
    	this.dispose();
    }//GEN-LAST:event_cancel_buttonActionPerformed
    
    /** Executed when the editing_panel has its current tab changed.
     *  Generated by NetBeans IDE 3.6. */
    private void editing_panelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_editing_panelStateChanged
        if(this.editing_panel.getSelectedIndex() == 1) {
        	this.etpd = this.etpd_panel.getETPD();
        	
        	if(this.etpd != null)
        		this.xml_area.setText(this.etpd.fullToXML(0));
        	else this.xml_area.setText("");
        }
    }//GEN-LAST:event_editing_panelStateChanged
    
    /** Returns the event time probability distribution manipulated by the GUI.
     * 
     *  @return The event time probability distribution manipulated by the GUI. */
    public EventTimeProbabilityDistribution getETPD() {
    	return this.etpd;
    }
    
    /* Attributes */
    // added manually    
    private EventTimeProbabilityDistribution etpd;
    private EventTimeProbabilityDistributionJPanel etpd_panel;
    
    // added by eclipse
    private static final long serialVersionUID = -1587154081514058244L;
    
    // added by NetBeans IDE 3.6
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttons_internal_panel;
    private javax.swing.JPanel buttons_panel;
    private javax.swing.JButton cancel_button;
    private javax.swing.JTabbedPane editing_panel;
    private javax.swing.JButton ok_button;
    private javax.swing.JPanel type_interna_panel;
    private javax.swing.JLabel type_label;
    private javax.swing.JPanel type_panel;
    private javax.swing.JTextArea xml_area;
    private javax.swing.JScrollPane xml_scroll;
    // End of variables declaration//GEN-END:variables
}