/* NormalEventTimeProbabilityDistributionJPanel.java */

/* The package of this class. */
package etpd;

/* Imported classes and/or interfaces. */
import javax.swing.JOptionPane;
import model.etpd.NormalEventTimeProbabilityDistribution;

/**
 * Implements the GUI panel able to configure
 * NormalEventTimeProbabilityDistribution objects.
 * 
 * @see NormalEventTimeProbabilityDistribution
 */
public class NormalEventTimeProbabilityDistributionJPanel extends
		EventTimeProbabilityDistributionJPanel {
	/* Methods. */
	/**
	 * Constructor.
	 * 
	 * @param etpd
	 *            The NormalEventTimeProbabilityDistribution object to be
	 *            configured.
	 */
	public NormalEventTimeProbabilityDistributionJPanel(
			NormalEventTimeProbabilityDistribution etpd) {
		this.initComponents();
		this.initComponents(etpd);
	}

	/**
	 * Initiates the components of the GUI. Generated by NetBeans IDE 3.6.
	 */
	private void initComponents() {// GEN-BEGIN:initComponents
		internal_panel = new javax.swing.JPanel();
		mean_panel = new javax.swing.JPanel();
		mean_label = new javax.swing.JLabel();
		mean_field = new javax.swing.JTextField();
		std_panel = new javax.swing.JPanel();
		std_label = new javax.swing.JLabel();
		std_field = new javax.swing.JTextField();
		seed_panel = new javax.swing.JPanel();
		seed_label = new javax.swing.JLabel();
		seed_field = new javax.swing.JTextField();
		seed_button = new javax.swing.JButton();

		setLayout(new java.awt.BorderLayout());

		internal_panel.setLayout(new java.awt.GridLayout(3, 0));

		mean_panel.setLayout(new java.awt.BorderLayout());

		mean_label.setText("Mean value ");
		mean_panel.add(mean_label, java.awt.BorderLayout.WEST);

		mean_field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		mean_field.setText("0");
		mean_field.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				mean_fieldKeyReleased(evt);
			}
		});

		mean_panel.add(mean_field, java.awt.BorderLayout.CENTER);

		internal_panel.add(mean_panel);

		std_panel.setLayout(new java.awt.BorderLayout());

		std_label.setText("Standard deviation ");
		std_panel.add(std_label, java.awt.BorderLayout.WEST);

		std_field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		std_field.setText("0");
		std_field.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				std_fieldKeyReleased(evt);
			}
		});

		std_panel.add(std_field, java.awt.BorderLayout.CENTER);

		internal_panel.add(std_panel);

		seed_panel.setLayout(new java.awt.BorderLayout());

		seed_label.setText("Seed ");
		seed_panel.add(seed_label, java.awt.BorderLayout.WEST);

		seed_field.setEditable(false);
		seed_field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		this.seed_field.setText(String
				.valueOf((int) System.currentTimeMillis()));
		seed_panel.add(seed_field, java.awt.BorderLayout.CENTER);

		seed_button.setText("Generate");
		seed_button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				seed_buttonActionPerformed(evt);
			}
		});

		seed_panel.add(seed_button, java.awt.BorderLayout.EAST);

		internal_panel.add(seed_panel);

		add(internal_panel, java.awt.BorderLayout.NORTH);

	}// GEN-END:initComponents

	/**
	 * Complements the initiation of the components of the GUI.
	 * 
	 * @param etpd
	 *            The NormalEventTimeProbabilityDistribution object to be
	 *            configured.
	 */
	private void initComponents(NormalEventTimeProbabilityDistribution etpd) {
		this.etpd = etpd;

		this.mean_field.setText(String.valueOf(this.etpd.getMean()));
		this.std_field.setText(String
				.valueOf(this.etpd.getStandard_deviation()));
		this.seed_field.setText(String.valueOf(this.etpd.getSeed()));
	}

	/**
	 * Executed when the seed_button is pressed. Generated by NetBeans IDE 3.6.
	 */
	private void seed_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_seed_buttonActionPerformed
		this.seed_field.setText(String
				.valueOf((int) System.currentTimeMillis()));
	}// GEN-LAST:event_seed_buttonActionPerformed

	/**
	 * Executed when the std_field changes. Generated by NetBeans IDE 3.6.
	 */
	private void std_fieldKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_std_fieldKeyReleased
		String str_std = this.std_field.getText().trim();
		if (str_std.length() > 0)
			try {
				Double.parseDouble(str_std);
			} catch (NumberFormatException e) {
				if (str_std.charAt(str_std.length() - 1) != '.') {
					JOptionPane.showMessageDialog(this,
							"The standard deviation must be a real number.",
							"Standard deviation error.",
							JOptionPane.ERROR_MESSAGE);
					this.std_field.setText("0");
				}
			}
	}// GEN-LAST:event_std_fieldKeyReleased

	/**
	 * Executed when the mean_field changes. Generated by NetBeans IDE 3.6.
	 */
	private void mean_fieldKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_mean_fieldKeyReleased
		String str_mean = this.mean_field.getText().trim();

		if (str_mean.length() > 0)
			try {
				Double.parseDouble(str_mean);
			} catch (NumberFormatException e) {
				if (str_mean.charAt(str_mean.length() - 1) != '.') {
					JOptionPane.showMessageDialog(this,
							"The mean value must be a real number.",
							"Mean value error.", JOptionPane.ERROR_MESSAGE);
					this.mean_field.setText("0");
				}
			}
	}// GEN-LAST:event_mean_fieldKeyReleased

	public model.etpd.EventTimeProbabilityDistribution getETPD() {
		try {
			double mean = Double.parseDouble(this.mean_field.getText().trim());
			double std = Double.parseDouble(this.std_field.getText().trim());
			int seed = Integer.parseInt(this.seed_field.getText().trim());

			this.etpd = new NormalEventTimeProbabilityDistribution(seed, mean,
					std);
		} catch (NumberFormatException e) {
			JOptionPane
					.showMessageDialog(
							this,
							"The mean and standard deviation values must be real numbers.",
							"Probability value error.",
							JOptionPane.ERROR_MESSAGE);

			if (this.etpd == null) {
				this.mean_field.setText("0");
				this.std_field.setText("0");
			} else
				this.initComponents(this.etpd);
		}

		return this.etpd;
	}

	/* Attributes. */
	// added manually
	private NormalEventTimeProbabilityDistribution etpd;

	// added by eclipse
	private static final long serialVersionUID = 8059655444485048434L;

	// added by NetBeans IDE 3.6
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel internal_panel;
	private javax.swing.JTextField mean_field;
	private javax.swing.JLabel mean_label;
	private javax.swing.JPanel mean_panel;
	private javax.swing.JButton seed_button;
	private javax.swing.JTextField seed_field;
	private javax.swing.JLabel seed_label;
	private javax.swing.JPanel seed_panel;
	private javax.swing.JTextField std_field;
	private javax.swing.JLabel std_label;
	private javax.swing.JPanel std_panel;
	// End of variables declaration//GEN-END:variables
}