/* AccelerationLimitationJPanel.java */

/* The package of this class. */
package limitation;

/* Imported classes and/or interfaces. */
import javax.swing.JOptionPane;
import model.limitation.AccelerationLimitation;
import model.limitation.Limitation;

/**
 * Implements the GUI panel able to configure AccelerationLimitation objects.
 * 
 * @see AccelerationLimitation
 */
public class AccelerationLimitationJPanel extends LimitationJPanel {
	/* Methods. */
	/**
	 * Constructor.
	 * 
	 * @param limitation
	 *            The AccelerationLimitation object to be configured.
	 */
	public AccelerationLimitationJPanel(AccelerationLimitation limitation) {
		this.initComponents();
		this.initComponents(limitation);
	}

	/**
	 * Initiates the components of the GUI. Generated by NetBeans IDE 3.6.
	 */
	private void initComponents() {// GEN-BEGIN:initComponents
		acceleration_panel = new javax.swing.JPanel();
		acceleration_label = new javax.swing.JLabel();
		acceleration_field = new javax.swing.JTextField();

		setLayout(new java.awt.BorderLayout());

		acceleration_panel.setLayout(new java.awt.BorderLayout());

		acceleration_label.setText("Acceleration value ");
		acceleration_panel.add(acceleration_label, java.awt.BorderLayout.WEST);

		acceleration_field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		acceleration_field.setText("1");
		acceleration_field.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				acceleration_fieldKeyReleased(evt);
			}
		});

		acceleration_panel
				.add(acceleration_field, java.awt.BorderLayout.CENTER);

		add(acceleration_panel, java.awt.BorderLayout.NORTH);

	}// GEN-END:initComponents

	/**
	 * Complements the initiation of the components of the GUI.
	 * 
	 * @param limitation
	 *            The AccelerationLimitation object to be configured.
	 */
	private void initComponents(AccelerationLimitation limitation) {
		this.limitation = limitation;
		this.acceleration_field.setText(String.valueOf(this.limitation
				.getAcceleration()));
	}

	/**
	 * Executed when the speed_field changes. Generated by NetBeans IDE 3.6.
	 */
	private void acceleration_fieldKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextField1KeyReleased
		String str_acceleration = this.acceleration_field.getText().trim();
		if (str_acceleration.length() > 0)
			try {
				double acceleration = Double.parseDouble(str_acceleration);
				if (acceleration < 0)
					throw new NumberFormatException();
			} catch (NumberFormatException e) {
				if (str_acceleration.charAt(str_acceleration.length() - 1) != '.') {
					JOptionPane
							.showMessageDialog(
									this,
									"The acceleration value must be a real non-negative number.",
									"Value error.", JOptionPane.ERROR_MESSAGE);
					this.acceleration_field.setText("1");
				}
			}
	}// GEN-LAST:event_jTextField1KeyReleased

	@Override
	public Limitation getLimitation() {
		try {
			double acceleration = Double.parseDouble(this.acceleration_field
					.getText().trim());

			if (acceleration < 0)
				throw new NumberFormatException();

			this.limitation = new AccelerationLimitation(acceleration);
		} catch (NumberFormatException e) {
			JOptionPane
					.showMessageDialog(
							this,
							"The acceleration value must be a real non-negative number.",
							"Value error.", JOptionPane.ERROR_MESSAGE);
			this.initComponents(this.limitation);
		}

		return this.limitation;
	}

	/* Attributes. */
	// added manually
	private AccelerationLimitation limitation;

	// added by Eclipse
	private static final long serialVersionUID = 8365395800217803247L;

	// added by NetBeans IDE 3.6
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel acceleration_label;
	private javax.swing.JPanel acceleration_panel;
	private javax.swing.JTextField acceleration_field;
	// End of variables declaration//GEN-END:variables
}