/* DepthLimitationJPanel.java */

/* The package of this class. */
package limitation;

/* Imported classes and/or interfaces. */
import model.limitation.DepthLimitation;
import model.limitation.Limitation;

/** Implements the GUI panel able to configure
 *  DepthLimitation objects.
 *  
 *  @see DepthLimitation */
public class DepthLimitationJPanel extends LimitationJPanel {    
	/* Methods. */
    /** Constructor.
     * 
     *  @param limitation The DepthLimitation object to be configured. */
    public DepthLimitationJPanel(DepthLimitation limitation) {
        this.initComponents();
        this.initComponents(limitation);
    }
    
    /** Initiates the components of the GUI.
     *  Generated by NetBeans IDE 3.6. */
    private void initComponents() {//GEN-BEGIN:initComponents
        depth_panel = new javax.swing.JPanel();
        depth_label = new javax.swing.JLabel();
        depth_spinner = new javax.swing.JSpinner();

        setLayout(new java.awt.BorderLayout());

        depth_panel.setLayout(new java.awt.BorderLayout());

        depth_label.setText("Depth value ");
        depth_panel.add(depth_label, java.awt.BorderLayout.WEST);

        depth_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                depth_spinnerStateChanged(evt);
            }
        });

        depth_panel.add(depth_spinner, java.awt.BorderLayout.CENTER);

        add(depth_panel, java.awt.BorderLayout.NORTH);

    }//GEN-END:initComponents
    
    /** Complements the initiation of the components of the GUI.
     * 
     *  @param limitation The DepthLimitation object to be configured. */
    private void initComponents(DepthLimitation limitation) {
    	this.limitation = limitation;
    	this.depth_spinner.setValue(new Integer(limitation.getDepth()));
    }
    
    /** Executed when the depth_spinner changes.
     *  Generated by NetBeans IDE 3.6. */
    private void depth_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_depth_spinnerStateChanged
        if(((Integer) this.depth_spinner.getValue()).intValue() < 0)
        	this.depth_spinner.setValue(new Integer(0));
    }//GEN-LAST:event_depth_spinnerStateChanged
    
	@Override
	public Limitation getLimitation() {
		this.limitation = new DepthLimitation(((Integer) this.depth_spinner.getValue()).intValue());
		return this.limitation;
	}    
    
    /* Attributes. */
    // added manually
    private DepthLimitation limitation;
    
    // added by Eclipse
	private static final long serialVersionUID = 15608458896239673L;
    
    // added by NetBeans IDE 3.6
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel depth_label;
    private javax.swing.JPanel depth_panel;
    private javax.swing.JSpinner depth_spinner;
    // End of variables declaration//GEN-END:variables
}