/* NodeNotFoundException.java */

/* The package of this class. */
package control.exception;

/** Exception generated every time no node is found from a given node id. */
public class NodeNotFoundException extends Exception {
	/* Attributes. */
	/* Generated by Eclipse IDE. */
	private static final long serialVersionUID = 6114269559752625814L;
}
